// This is an autogenerated header file
#ifndef JULIA_VERSION_H
#define JULIA_VERSION_H
#define JULIA_VERSION_STRING "0.6.0"
#define JULIA_VERSION_MAJOR 0
#define JULIA_VERSION_MINOR 6
#define JULIA_VERSION_PATCH 0
#define JULIA_VERSION_IS_RELEASE 1
#endif
